let a = {
  "code": 0,
  "message": "ok",
  "data": [{
    "name_py": ":",
    "data": [{
      "id": 47270,
      "name": ",:在12346.",
      "tel": null,
      "name_py": ":",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "B",
    "data": [{
      "id": 35829,
      "name": "吧osmosis",
      "tel": null,
      "name_py": "B",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 1
    }]
  }, {
    "name_py": "G",
    "data": [{
      "id": 35756,
      "name": "隔音",
      "tel": null,
      "name_py": "G",
      "name_color": "#58C7FF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 1
    }, {
      "id": 35878,
      "name": "共鸣后",
      "tel": null,
      "name_py": "G",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 1
    }, {
      "id": 36215,
      "name": "共鸣",
      "tel": null,
      "name_py": "G",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 1
    }]
  }, {
    "name_py": "H",
    "data": [{
      "id": 35757,
      "name": "红花油兔兔",
      "tel": null,
      "name_py": "H",
      "name_color": "#58C7FF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 1
    }, {
      "id": 35891,
      "name": "韩国模棱两可里",
      "tel": null,
      "name_py": "H",
      "name_color": "#74E8D5",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "J",
    "data": [{
      "id": 35888,
      "name": "京剧团",
      "tel": null,
      "name_py": "J",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "K",
    "data": [{
      "id": 35889,
      "name": "卡册大的阿拉巴啊",
      "tel": null,
      "name_py": "K",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 35890,
      "name": "可口可乐了可口可乐了了",
      "tel": null,
      "name_py": "K",
      "name_color": "#74E8D5",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "M",
    "data": [{
      "id": 45,
      "name": "默认工人",
      "tel": "15682383223",
      "name_py": "M",
      "name_color": "#be92e8",
      "is_deleted": 0,
      "is_self": 1,
      "is_in_work_note": 0
    }, {
      "id": 35871,
      "name": "迷宫",
      "tel": null,
      "name_py": "M",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 35875,
      "name": "马上到！破破破破破",
      "tel": null,
      "name_py": "M",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "N",
    "data": [{
      "id": 35880,
      "name": "您婆婆婆婆嫌弃我婆婆",
      "tel": null,
      "name_py": "N",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "O",
    "data": [{
      "id": 16980,
      "name": "哦是呀呀呀呀你外婆",
      "tel": null,
      "name_py": "O",
      "name_color": "#58C7FF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "Q",
    "data": [{
      "id": 35760,
      "name": "全身照一张张",
      "tel": null,
      "name_py": "Q",
      "name_color": "#74E8D5",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 35887,
      "name": "去咯哦哦哦",
      "tel": null,
      "name_py": "Q",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "R",
    "data": [{
      "id": 35877,
      "name": "如行尸走肉行尸走肉",
      "tel": null,
      "name_py": "R",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "S",
    "data": [{
      "id": 35758,
      "name": "所以爱",
      "tel": null,
      "name_py": "S",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 35883,
      "name": "孙婆婆我婆婆一起",
      "tel": null,
      "name_py": "S",
      "name_color": "#A4BFFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 35892,
      "name": "生气咯现在",
      "tel": null,
      "name_py": "S",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "T",
    "data": [{
      "id": 35872,
      "name": "吞噬一切得",
      "tel": null,
      "name_py": "T",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 35886,
      "name": "图文信息技术有限公司",
      "tel": null,
      "name_py": "T",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }, {
      "id": 36091,
      "name": "听我妈在",
      "tel": null,
      "name_py": "T",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "W",
    "data": [{
      "id": 35876,
      "name": "我哦哦哦谢谢",
      "tel": null,
      "name_py": "W",
      "name_color": "#79BAFF",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }, {
    "name_py": "Z",
    "data": [{
      "id": 35873,
      "name": "早睡早起你婆婆破坏",
      "tel": null,
      "name_py": "Z",
      "name_color": "#74E8D5",
      "is_deleted": 0,
      "is_self": 0,
      "is_in_work_note": 0
    }]
  }]
}